germline_classification/urls.py
from django.urls import path

from . import views

app_name = "germline_classification"

urlpatterns = [
    path('', views.home, name='home'),
    path('pending_classifications', views.pending_classifications, name='pending_classifications'),
    path('completed_classifications', views.completed_classifications, name='completed_classifications'),
    path('classify_variant/<str:variant_classification_id>', views.classify_variant, name='classify_variant')
]

somatic_variant_db/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path(f'{settings.URL_PREFIX}admin/', admin.site.urls),
    path(f'{settings.URL_PREFIX}', include('analysis.urls')),
    path(f'{settings.URL_PREFIX}swgs/', include('swgs.urls'))
]

swgs/urls.py
from django.contrib.auth import views as auth_view
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_swgs, name="home_swgs"),
    path('view_runs/', views.view_runs, name="view_runs"),
    path('ajax/submit_variant_selections/', views.ajax, name='ajax'),
    path('view_patient_analysis/<str:patient_analysis_id>', views.view_patient_analysis, name="view_patient_analysis"),
    path('view_panels/', views.view_panels, name="view_panels"),
    path('view_panel/<str:panel_id>', views.view_panel, name="view_panel"),
    path('view_indication/<str:indication_id>', views.view_indication, name="view_indication")
]

germline_classification/forms.py
from django import forms
from django.template.defaultfilters import linebreaks_filter
from django.utils.safestring import mark_safe

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, HTML
from crispy_forms.bootstrap import InlineCheckboxes, InlineRadios

from .models import ClassificationCriteria, Classification

def get_choices_and_help_message(list_of_codes):

    # query for the codes of interest
    codes = ClassificationCriteria.objects.filter(
        code__code__in=list_of_codes
    )

    # For choices we want a list of code/strength combos
    choices = [(choice.id, choice.form_display()) for choice in codes]
    choices.append((None, "None Apply"))

    # for help we want a list of codes and their descriptions formatted for rendering
    help_messages = [(choice.code.code, choice.code.description) for choice in codes]
    help_messages_text = ""
    used_codes = []
    for message in help_messages:
        if message[0] not in used_codes:
            text = message[1].replace('\n', ' ')
            text = text.replace('\r', ' ')
            formatted_message = rf"{message[0]}: {text}<br>"
            help_messages_text += formatted_message
            used_codes.append(message[0])

    return choices, help_messages_text

class ClassifyForm(forms.Form):
    """
    Classify a single variant
    """

    # Population Evidence
    population_choices, population_help = get_choices_and_help_message(["PS4", "PM2", "BA1", "BS1", "BS2"])
    population_codes = forms.MultipleChoiceField(
        label = "Population Evidence",
        help_text = mark_safe(population_help),
        choices = population_choices,
        widget=forms.CheckboxSelectMultiple
    )

    # Predictive and Computational Evidence
    predictive_choices, predictive_help = get_choices_and_help_message(["PVS1", "PS1", "PM5", "PM4", "PP3", "BP1", "BP4", "BP7"])
    predictive_codes = forms.MultipleChoiceField(
        label = "Predictive and Computational Evidence",
        help_text = mark_safe(predictive_help),
        choices = predictive_choices,
        widget = forms.CheckboxSelectMultiple
    )

    # Functional Evidence
    functional_choices, functional_help = get_choices_and_help_message(["PS3", "PM1", "PP2", "BS3"])
    functional_codes = forms.MultipleChoiceField(
        label = "Functional Evidence",
        help_text = mark_safe(functional_help),
        choices = functional_choices,
        required=False,
        widget = forms.CheckboxSelectMultiple
    )

    # De Novo Evidence
    de_novo_choices, de_novo_help = get_choices_and_help_message(["PS2", "PM6"])
    de_novo_codes = forms.ChoiceField(
        label = "De Novo Evidence",
        help_text = mark_safe(de_novo_help),
        choices = de_novo_choices
    )

    # Segregation Evidence
    segregation_choices, segregation_help = get_choices_and_help_message(["PP1", "BS4"])
    segregation_codes = forms.ChoiceField(
        label = "Segregation Evidence",
        help_text = mark_safe(segregation_help),
        choices = segregation_choices
    )

    # Allelic Evidence
    allelic_choices, allelic_help = get_choices_and_help_message(["PM3", "BP2"])
    allelic_codes = forms.ChoiceField(
        label = "Allelic Evidence",
        help_text = mark_safe(allelic_help),
        choices = allelic_choices
    )

    # Phenotype Data
    phenotype_choices, phenotype_help = get_choices_and_help_message(["PP4", "BP5"])
    phenotype_codes = forms.ChoiceField(
        label = "Phenotype Evidence",
        help_text = mark_safe(phenotype_help),
        choices = phenotype_choices
    )

    def __init__(self, *args, **kwargs):
        super(ClassifyForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = "POST"
        self.helper.label_class = "font-weight-bold"
        self.helper.add_input(
            Submit("submit", "Classify Variant", css_class="btn btn-info w-100")
            )
        
        self.helper.layout = Layout(   
            InlineCheckboxes("population_codes"),
            InlineCheckboxes("predictive_codes"),
            InlineCheckboxes("functional_codes"),
            InlineRadios("de_novo_codes"),
            InlineRadios("segregation_codes"),
            InlineRadios("allelic_codes"),
            InlineRadios("phenotype_codes")
        )

germline_classification/views.py
import datetime

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .forms import *
from .utils import *

@login_required
def home(request):
    return render(request, 'germline_classification/home.html')

@login_required
def pending_classifications(request):
    """
    Get and display all pending variant classifications
    """

    all_pending_classifications  = get_classifications("pending", False)

    context = {
        "classifications": all_pending_classifications
    }

    return render(request, "germline_classification/pending_classifications.html", context)

@login_required
def completed_classifications(request):
    """
    Get and display all pending variant classifications
    """

    all_pending_classifications  = get_classifications("completed", True)

    context = {
        "classifications": all_pending_classifications
    }

    return render(request, "germline_classification/completed_classifications.html", context)


@login_required
def classify_variant(request, variant_classification_id):
    """
    Classify a single variant
    """
    #TODO ADD ID IN TO THIS

    # set up forms 
    classify_form = ClassifyForm()
    warnings = []
    success = []
    final_classification = ""

    # get classification object
    variant_classification_obj = VariantClassification.objects.get(pk=variant_classification_id)
    classification_obj = variant_classification_obj.classification

    # get variant info
    variant_display = variant_classification_obj.display_variant_info()

    # check if user is signed off to perform germline classifications
    in_germline_classification_user_group = request.user.groups.filter(name="germline_classification").exists()

    if request.method == 'POST':

        classify_form = ClassifyForm(request.POST)
        print(classify_form.is_valid())
        if classify_form.is_valid():

            # get user including competence status
            current_user = request.user
            in_germline_classification_user_group = current_user.groups.filter(name="germline_classification").exists()

            # get time
            now = datetime.datetime.today()

            # get data from form
            population_codes = classify_form.cleaned_data["population_codes"]
            predictive_codes = classify_form.cleaned_data["predictive_codes"]
            functional_codes = classify_form.cleaned_data["functional_codes"]
            de_novo_codes = classify_form.cleaned_data["de_novo_codes"]
            segregation_codes = classify_form.cleaned_data["segregation_codes"]
            allelic_codes = classify_form.cleaned_data["allelic_codes"]
            phenotype_codes = classify_form.cleaned_data["phenotype_codes"]
            
            # get all the codes together
            all_codes = []
            for code_list in ([population_codes, predictive_codes, functional_codes, de_novo_codes, segregation_codes, allelic_codes, phenotype_codes]):
                if not isinstance(code_list, list):
                    code_list = [code_list]
                for code in code_list:
                    if code != "None":
                        all_codes.append(int(code))

            # create a new classification object
            # update information with user and time
            classification_obj.user = current_user
            classification_obj.signoff_time = now

            # add codes
            for code in all_codes:
                code_obj = ClassificationCriteria.objects.get(id=code)
                classification_obj.criteria_applied.add(code_obj)
            
            classification, score = classification_obj.perform_classification()
            final_classification = f"{classification} ({score})"
            #context["final_classification"] = final_classification

            # set classification to diagnostic only if user is signed off for this
            if in_germline_classification_user_group:
                classification_obj.diagnostic = True

            # set classification as complete
            classification_obj.complete = True
            classification_obj.save()

            # if this was a training case then we still need this variant to be classified
            if not in_germline_classification_user_group:
                # reset pk to duplicate object
                classification_obj.pk = None
                classification_obj.save()
                success.append("Classification complete! This was a training case only.")
            else:
                success.append("Classification complete!")

            #return redirect('classify_variant')

    context = {
        "variant_display": variant_display,
        "classify_form": classify_form,
        "warning": warnings,
        "success": success,
        "final_classification": final_classification
    }

    return render(request, "germline_classification/classify_variant.html", context)

germline_classification/templates/germline_classification/classify_variant.html
{% extends 'analysis/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<div class="container-fluid breadcrumbs-custom">
  <div class="container">
    <ol class="breadcrumb" style="background-color: transparent;">
      <li class="breadcrumb-item"><a href="{% url 'germline_classification:home' %}"><span class="fa fa-home"></span></a></li>
    </ol>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
  
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4"><i class="fa fa-dna"></i> Germline Classification</h1>
      <p>Classify variants using the <a href="https://www.acgs.uk.com/media/12533/uk-practice-guidelines-for-variant-classification-v12-2024.pdf">ACGS 2024 Guidelines</a></p>
      </br>
      <h3>Classifying {{ variant_display }}</h3>
      </br>
      {% crispy classify_form %}
      </br>
      <h3>This variant is <strong>{{ final_classification }}</strong></h3>
    </div>
  </div>
</div>


{% endblock %}

germline_classification/templates/germline_classification/completed_classifications.html
{% extends 'analysis/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<div class="container-fluid breadcrumbs-custom">
  <div class="container">
    <ol class="breadcrumb" style="background-color: transparent;">
      <li class="breadcrumb-item"><a href="{% url 'germline_classification:home' %}"><span class="fa fa-home"></span></a></li>
      <li class="breadcrumb-item"><a href="{% url 'germline_classification:completed_classifications' %}">Completed Classifications</a></li>
    </ol>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
<h1>Completed Classifications</h1>
<br>
<br>
<h3>Spiel</h3>
<br>
<br>
<table class="table">
    <thead>
        <tr>
            <th class="col-md-4">Variant</th>
            <th class="col-md-8">Previous Classifications</th>
        </tr>
    </thead>
    <tbody>
        {% for c in classifications %}
        <tr>
            <td>
              {{ c.genomic_coordinate }}
              <br>
              {{ c.gene }}
              <br>
              {{ c.hgvsc }}
              <br>
              {{ c.hgvsp }}
            </td>
            
            <td>
              <table>
                <tr>  
                  <td>Assay</td>
                  <td>User</td>
                  <td>Date Classified</td>
                  <td>Final Classification</td>
                  <td>Score</td>
                </tr>
                {% for pc in c.previous_classifications %}
                <tr>
                  <td>{{ pc.assay }}</td>
                  <td>{{ pc.user }}</td>
                  <td>{{ pc.signoff_time }}</td>
                  <td>{{ pc.final_classification }} </td>
                  <td>{{ pc.total_score }}</td>
                </tr>
                {% endfor %}
              </table>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

germline_classification/templates/germline_classification/home.html
{% extends 'analysis/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<div class="container-fluid breadcrumbs-custom">
  <div class="container">
    <ol class="breadcrumb" style="background-color: transparent;">
      <li class="breadcrumb-item"><a href="{% url 'germline_classification:home' %}"><span class="fa fa-home"></span></a></li>
    </ol>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
<h1>Germline Classification</h1>
<a class="btn btn-secondary" href="{% url 'germline_classification:pending_classifications' %}" role="button">
    View Pending Classifications
</a>
<a class="btn btn-secondary" href="{% url 'germline_classification:completed_classifications' %}" role="button">
  View Completed Classifications
</a>
</div>
{% endblock %}

germline_classification/templates/germline_classification/pending_classifications.html
{% extends 'analysis/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<div class="container-fluid breadcrumbs-custom">
  <div class="container">
    <ol class="breadcrumb" style="background-color: transparent;">
      <li class="breadcrumb-item"><a href="{% url 'germline_classification:home' %}"><span class="fa fa-home"></span></a></li>
      <li class="breadcrumb-item"><a href="{% url 'germline_classification:pending_classifications' %}">Pending Classifications</a></li>
    </ol>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
<h1>Pending Classifications</h1>
<br>
<br>
<h3>Spiel</h3>
<br>
<br>
<table class="table">
    <thead>
        <tr>
            <th class="col-md-4">Variant</th>
            <th class="col-md-1">Gene</th>
            <th class="col-md-4">HGVSc / HGVSp</th>
            <th class="col-md-1">Origin</th>
            <th class="col-md-2">Classify</th>
        </tr>
    </thead>
    <tbody>
        {% for c in classifications %}
        <tr>
            <td>{{ c.genomic_coordinate }}</td>
            <td>{{ c.gene }}</td>
            <td>{{ c.hgvsc }}<br>{{ c.hgvsp }}</td>
            <td>{{ c.origin }}</td>
            <td><a class="btn btn-secondary btn-block" href="{% url 'germline_classification:classify_variant' c.id %}">Classify</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

germline_classification/templates/germline_classification/test.html
{% extends 'analysis/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<br>
{% endblock %}

{% block content %}
<div class="container-fluid">
  
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4"><i class="fa fa-dna"></i> Germline Classification</h1>
    </div>
  </div>
</div>


{% endblock %}